disabled_rules:
- trailing_whitespace
- opening_brace
- xctfail_message

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

line_length:
    warning: 150
    error: 200
    ignores_comments: true
#    ignores_function_declarations: true
#    ignores_urls: true

function_body_length:
    warning: 100
    error: 150

function_parameter_count:
    warning: 10
    error: 20

type_body_length:
    warning: 400
    error: 700

file_length:
    warning: 500
    error: 1000
    ignore_comment_only_lines: true

#cyclomatic_complexity:
#    warning: 15
#    error: 25

identifier_name:
  min_length: 1

type_name:
  excluded: [Run__App, Run__UITestsLaunchTests, Run__UITests]
  
large_tuple:
  warning: 5
  error: 10

nesting:
  type_level:
    warning: 2
    error: 5

reporter: "xcode"
